[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_gitignore = "True"
line_length = 119

[tool.black]
line-length = 119
target-version = ['py37']
